tracetool: adjust relative path for Windows path
On Windows, os.path.relpath will return a Windows path even if the
argument was a posix path. This results with the generated code having "\"
which is the escape character in C.

trace/trace-util.h:2055:10: warning: unknown escape sequence: '\s'
 2055 | #line 91 "..\src\util\trace-events"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
trace/trace-util.h:2055:10: error: incomplete universal character name \u

qemu#27