squash! Add traces generation
This fixes the following:

  xxx/src/qemu-traces.c: In function 'exec_trace_flush':
  xxx/src/qemu-traces.c:133:5: error: ignoring return value of 'fwrite',
           declared with attribute warn_unused_result [-Werror=unused-result]
     fwrite(trace_entries, len, 1, tracefile);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

2020-04-08  KONRAD Frederic  <konrad@adacore.com>
        * qemu-traces.c: check for fwrite return value (T514-016).

TN: T514-016
Change-Id: Ic9371129240f5340faf298b4fd8e7e1a921964e6