squash! Add traces generation
This fixes:
  xxx/accel/tcg/cpu-exec.c: In function 'trace_after_exec':
  xxx/accel/tcg/cpu-exec.c:794:33: error: cast to pointer from integer of
  different size [-Werror=int-to-pointer-cast]
    TranslationBlock *last_tb = (TranslationBlock *)(next_tb & ~TB_EXIT_MASK);
                                ^

Use uintptr_t for trace_after_exec to avoid the cast from unsigned long.

2020-05-19  Frederic Konrad  <konrad@adacore.com>
    * accel/tcg/cpu-exec.c: use uintptr_t instead of unsigned long for
                            trace_after_exec argument (T514-018).

TN: T514-018
Change-Id: I1c09aeea8af508b80fa14c122741ca8d2f818389