Makefile: drop qemu-storage-y and it's qapi files.
There is an odd bug in the Makefile: qapi-gen is called twice, and in the
end overwrite qapi/qapi-types-crypto.h without some required struct.  The
result is a build failure with j=1:

xxx/qapi/qapi-types-crypto.h:176:33: error: field 'qcow' has incomplete type
  176 |         QCryptoBlockOptionsQCow qcow;
      |                                 ^~~~

TN: T804-022
Change-Id: Ie5728c329e60392f171ba22c9760ad5863e8868c